import Head from 'next/head'
import { useEffect, useRef } from 'react'
import MuiCustomizedSwitch from '../components/MuiCustomizedSwitch';
import RoomExperience from '../WebglExperience/roomExperience';

export default function Home() {
  const canvas = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    let experience: RoomExperience;
    if (canvas.current) {
      experience = new RoomExperience(canvas.current);
      (window as any).experience = experience;
      // console.log(experience)
    }
  }, [canvas])
  return (
    <div>
      <Head>
        <title>Bruno-Simon Room Youtube Stream</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className='webGl-Wrapper'>
        <canvas className='webGl-canvas' ref={canvas}></canvas>
        <MuiCustomizedSwitch />
      </main>

    </div>
  )
}
