import Head from 'next/head'
import { useCallback, useEffect, useRef } from 'react'
import LoadingOverlay from '../components/LoadingOverlay';
import MuiCustomizedSwitch from '../components/MuiCustomizedSwitch';
import MusicPlayIcons from '../components/MusicPlayIcons';
import RoomExperience from '../WebglExperience/roomExperience';

export default function Home() {
  const canvas = useRef<HTMLCanvasElement>(null);
  const experience = useRef<RoomExperience | null>(null);

  const togglePlay = useCallback((value: boolean) => {
    experience.current?.world.backgroundMusic.onToggleState(value)
  }, [])

  useEffect(() => {
    if (canvas.current) {
      experience.current = new RoomExperience(canvas.current);
      (window as any).experience = experience;
      // console.log(experience)
    }

    return () => experience.current?.destroyExperience();
  }, [canvas])
  return (
    <div className='app-wrapper'>
      <Head>
        <title>Bruno-Simon Room Youtube Stream</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <LoadingOverlay />
      <main className='webGl-Wrapper'>
        <canvas className='webGl-canvas' ref={canvas}></canvas>
        <MuiCustomizedSwitch />
        <MusicPlayIcons togglePlay={togglePlay} />
      </main>

    </div>
  )
}
